export const LANDING = '/'
export const SIGN_UP = '/sign-up'
export const SIGN_IN = '/sign-in'
export const HOME = '/home'
export const ACCOUNT = '/account'
export const PASSWORD_FORGET = '/pw-forget'
export const VOTE = '/vote/:id'
export const STORY = '/story'